spring:
  config:
    import: "optional:file:env.properties"
    
  security:
    oauth2:
      resourceserver:
        jwt:
          issuer-uri: ${COGNITO_ISSUER_URI}

  data:
    mongodb:
      uri: ${MONGO_URI}
      database: ${MONGO_DATABASE}